name: Code Coverage

on:
  pull_request:
    branches:
      - main  # adjust this to your main branch name

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage

    - name: Run tests with coverage
      run: |
        DIR=$(pwd)
        coverage run --source=$DIR -m unittest tests/*_tests.py

    - name: Generate coverage report
      run: coverage report -m

